// Code generated by Slice Machine. DO NOT EDIT.

import Accomplishments from './Accomplishments';
import Clients from './Clients';
import Footer from './Footer';
import FooterBottom from './FooterBottom';
import Hero from './Hero';
import Image from './Image';
import ImageSlider from './ImageSlider';
import LargeImage from './LargeImage';
import Location from './Location';
import Logo from './Logo';
import Member from './Member';
import MenuList from './MenuList';
import Mosaic from './Mosaic';
import NextProject from './NextProject';
import ProjectDescription from './ProjectDescription';
import ProjectHero from './ProjectHero';
import Projects from './Projects';
import ProjectsPreview from './ProjectsPreview';
import Richtext from './Richtext';
import Service from './Service';
import ServicesPreview from './ServicesPreview';
import Story from './Story';
import Team from './Team';
import TeamPreview from './TeamPreview';
import TwoImages from './TwoImages';
import VideoSingle from './VideoSingle';
import VideoSlider from './VideoSlider';

export {
	Accomplishments,
	Clients,
	Footer,
	FooterBottom,
	Hero,
	Image,
	ImageSlider,
	LargeImage,
	Location,
	Logo,
	Member,
	MenuList,
	Mosaic,
	NextProject,
	ProjectDescription,
	ProjectHero,
	Projects,
	ProjectsPreview,
	Richtext,
	Service,
	ServicesPreview,
	Story,
	Team,
	TeamPreview,
	TwoImages,
	VideoSingle,
	VideoSlider,
};

export const components = {
	accomplishments: Accomplishments,
	clients: Clients,
	footer: Footer,
	footer_bottom: FooterBottom,
	hero: Hero,
	image: Image,
	image_slider: ImageSlider,
	large_image: LargeImage,
	location: Location,
	logo: Logo,
	member: Member,
	menu_list: MenuList,
	collage: Mosaic,
	next_project: NextProject,
	project_description: ProjectDescription,
	project_hero: ProjectHero,
	projects: Projects,
	projects: ProjectsPreview,
	richtext: Richtext,
	service: Service,
	services: ServicesPreview,
	story: Story,
	team: Team,
	team_preview: TeamPreview,
	two_images: TwoImages,
	video_single: VideoSingle,
	video_slider: VideoSlider,
};
